/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ERC1132"): TruffleContracts.ERC1132Contract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC20Burnable"): TruffleContracts.ERC20BurnableContract;
      require(name: "ERC20Detailed"): TruffleContracts.ERC20DetailedContract;
      require(name: "ERC20Mintable"): TruffleContracts.ERC20MintableContract;
      require(name: "IERC1132"): TruffleContracts.IERC1132Contract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "LockableToken"): TruffleContracts.LockableTokenContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "MinterRole"): TruffleContracts.MinterRoleContract;
      require(name: "RebornDollar"): TruffleContracts.RebornDollarContract;
    }
  }
}
